version: '2.0'
services:
  golang-dev:
    image: "m9rco/go:1.10.8-dev"
    ports:
      - "2222:22"
      - "80:80"
      - "1234:1234"
    volumes:
      - $PWD:/app:rw
    depends_on:
      - etcd
      - mongodb
    networks:
      exile_network:
        ipv4_address: 172.16.238.2
  etcd:
    image: "m9rco/etcd:3.3.13"
    ports:
      - "2379:2379"
      - "2380:2380"
    ulimits:
      nproc: 65535
    restart: always
    networks:
      exile_network:
        ipv4_address: 172.16.238.3
  mongodb:
    image: "m9rco/mongodb:3.6.7"
    ports:
      - "27017:27017"
    volumes:
      - $PWD:/app:rw
    networks:
      exile_network:
        ipv4_address: 172.16.238.4
networks:
  exile_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1